### ISSUE TITLE
Error when selecting S3 Bucket

### ISSUE THREAD

**Issue by asmerkin** [inpsyde/backwpup#112]
**Describe the bug**

I get this when I want to select a s3 Bucket after introducing my AWS keys

```
Fatal error: Uncaught TypeError: Argument 1 passed to Aws\Handler\GuzzleV6\GuzzleHandler::Aws\Handler\GuzzleV6\{closure}() must be an instance of Exception, instance of Error given, called in /var/www/web/wp-content/plugins/backwpup/vendor/guzzlehttp/promises/src/Promise.php on line 203 and defined in /var/www/web/wp-content/plugins/backwpup/vendor/aws/aws-sdk-php/src/Handler/GuzzleV6/GuzzleHandler.php:45 Stack trace: #0 /var/www/web/wp-content/plugins/backwpup/vendor/guzzlehttp/promises/src/Promise.php(203): Aws\Handler\GuzzleV6\GuzzleHandler::Aws\Handler\GuzzleV6\{closure}() #1 /var/www/web/wp-content/plugins/backwpup/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler() #2 /var/www/web/wp-content/plugins/backwpup/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}() #3 /var/www/web/wp-content/plugins/backwpup/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(118): GuzzleHttp\Promise\TaskQueue->run() #4 /var/www/web/wp-co in /var/www/web/wp-content/plugins/backwpup/vendor/aws/aws-sdk-php/src/Handler/GuzzleV6/GuzzleHandler.php on line 45
```

**To Reproduce**
1. Create a Job
2. Select s3 as destination service. 
3. introuduce your aws credentials. 
4. Try to select a bucket. 

**Expected behavior**
I expected to be able to select a bucket and then save my settings. 

**System (please complete the following information):**
- OS: Linux
- Version Ubuntu 20.04

**Additional context**

**Comment by gaambo** [comment]
Seems to be a duplicate of #94 and #113 - is there an ETA for a fix for this?
